/**
 * AUTO-GENERATED REGISTRY FILE
 * Do not edit this file manually.
 * It is generated by scripts/generate-registry.js at build time.
 */

import * as t0 from './projects/anniversary/index.js';
import * as t1 from './projects/love_letter/index.js';

export const PROJECT_REGISTRY = {
  'anniversary': t0,
  'love_letter': t1,
};
