name = "romancespace"
main = "src/index.js"
compatibility_date = "2024-03-05"

# [vars]
# API_SECRET = "your-secret"

routes = [
  { pattern = "romancespace.885201314.xyz", custom_domain = true },
  { pattern = "*.romancespace.885201314.xyz", zone_name = "885201314.xyz" }
]

[[kv_namespaces]]
binding = "ROMANCESPACE_KV"
id = "726287eac5274a80b9df18217d43b0f0"

# [[d1_databases]]
# binding = "DB"
# database_name = "romancespace-db"
# database_id = "your-d1-id"
